//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public string CartItemID { get; set; }
        public string CartID { get; set; }
        public string MemberID { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public string ProductID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}
