//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvetoryLog
    {
        public string TransactionID { get; set; }
        public string ProductID { get; set; }
        public string InventoryID { get; set; }
        public int QuantityChg { get; set; }
        public string TransactionDate { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Product Product { get; set; }
    }
}
