//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemOrder()
        {
            this.MemPayments = new HashSet<MemPayment>();
        }
    
        public string MemOrderID { get; set; }
        public string MemberID { get; set; }
        public string CartID { get; set; }
        public string OrderDate { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Status { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemPayment> MemPayments { get; set; }
    }
}
