//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemPayment
    {
        public string MemPaymentID { get; set; }
        public string MemOrderID { get; set; }
        public string PaymentMethod { get; set; }
        public double Amount { get; set; }
        public string PaymentDate { get; set; }
    
        public virtual MemOrder MemOrder { get; set; }
    }
}
