//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPic
    {
        public string ImageID { get; set; }
        public string ProductID { get; set; }
        public string ImageURL { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
