//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurPayment
    {
        public string PurPaymentID { get; set; }
        public string SupplierID { get; set; }
        public string PurchaseID { get; set; }
        public string PaymentMethod { get; set; }
        public double Amount { get; set; }
        public string PaymentDate { get; set; }
    
        public virtual PurOrder PurOrder { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
