//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string ReservationID { get; set; }
        public string MemberID { get; set; }
        public string ReserveDate { get; set; }
        public byte[] Timestamp { get; set; }
        public int NumOfPpl { get; set; }
        public string Status { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
