//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGM_Organical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string StaffEmail { get; set; }
        public string StaffIC { get; set; }
        public string Hash { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string RoleID { get; set; }
        public string Position { get; set; }
        public double Salary { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
